import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client'

// export const getStaticProps = async () => {
//    const client = new ApolloClient({
//       uri: 'https://countries.trevorblades.com/',
//       cache: new InMemoryCache(),
//    })

//    const { data } = await client.query({
//       query: gql`
//          {
//             continents {
//                name
//                countries {
//                   code
//                   name
//                   capital
//                   emoji
//                   languages {
//                      name
//                   }
//                }
//             }
//          }
//       `,
//    })

//    return {
//       props: {
//          continents: data.continents,
//       },
//    }
// }

export default function Home({ continents }) {
   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <main>
            {/* {continents.map((continent) => (
               <div key={continent.name}>
                  <a>{continent.name}</a>
                  {continent.countries.map((country) => (
                     <Link href={`/country/${country.code}`} key={country.code}>
                        <a>{country.name}</a>
                     </Link>
                  ))}
               </div>
            ))} */}

            <div>home</div>
         </main>
      </div>
   )
}
